### ISSUE TITLE
Example app for React Native

### ISSUE THREAD

**Issue by shreyasthiagaraj** [blockstack/blockstack-ios#32]
An app showing end-to-end how to configure and get React Native apps running using the Blockstack iOS SDK would be very useful to the community.

**Comment by larrysalibra** [comment]
We've got an example react native app running on android thanks to @friedger. 

I opened an issue to add iOS support. 

https://github.com/larrysalibra/blockstack-react-native/issues/2

Once we get iOS support added, we can publish a blockstack react native module to npm so that devs can easily add support for blockstack on both their ios and android native apps: 
https://github.com/larrysalibra/blockstack-react-native/issues/3
