### ISSUE TITLE
Example app sign-in gets stuck

### ISSUE THREAD

**Issue by michalciurus** [blockstack/blockstack-ios#5]
Really excited with the early release of the SDK! Great job. A little issue's stopping me with continuing further development.

When I click on "Sign in with Blockstack" in example app I get taken to a webpage and get stuck there as it says: "Sign in request: Loading app details..."

Steps:

1. Run `npm install`, `npm start` in webapp folder. Make sure that `http://localhost:8080` works.
2. Run example project
3. Click on `Sign in with Blockstack`

Result: Gets stuck with a message "Sign in request: Loading app details..."

**Comment by yknl** [comment]
@michalciurus the reason it's getting stuck is because `browser.blockstack.org` is trying to load the app manifest file from `http://localhost:8080`, which it can't reach. There are 2 ways to get this to work: 

1) Host your web app on a public domain e.g. http://myblockstackapp.com. This is the way to go for production Blockstack iOS apps.
2) Run the [Blockstack browser](https://github.com/blockstack/blockstack-browser) locally and point the app to it by changing `BlockstackConstants.BrowserWebAppAuthEndpoint`to http://localhost:3000/auth

**Comment by michalciurus** [comment]
Oh, ok. I followed the steps in the Readme and I assumed that would be enough to run the example project.

It would be awesome if the Readme would contain all the steps needed to run the example app and it worked :)

**Comment by michalciurus** [comment]
Yeah it worked @yknl! The port was `8888` though not `3000`. Thanks!

Although there's one crash, because I have no name :D Will create a PR
