### ISSUE TITLE
Proposal: New ios Demo Application

### ISSUE THREAD

**Issue by stackatron** [blockstack/blockstack-ios#84]
We'd like to provide more support for mobile developers on iOS; our existing sample is only a simple hello-world.

**Comment by shreyasthiagaraj** [comment]
https://paper.dropbox.com/doc/Better-iOS-Sample--AkHU7fFpszfnWlcDKSvNcm7pAQ-4yx0gju37Vp10HCDsKOFV

**Comment by moxiegirl** [comment]
@shreyasthiagaraj I don't see your new example code in the repo.  Do you consider that the solution to this tutorial issue? I don't actually see any instructions or documentation on it. Where did you add them?

The solution in your proposal only points to the github repo which we do not have page analytics on a GitHub repo.  We can get them on the docs. I would recommend we actually put documentation on your new tutorial there.

**Regarding our existing tutorial**

This page actually gets 124 page views per month.  It accurately depicts the flow for building an IOS app. I am retesting our existing hello-world https://docs.blockstack.org/develop/zero_to_dapp_1.html and updating it.

I would agree that our tutorials could be stickier but I don't think we are clear on what the problem is with the existing tutorial.  Many of the comments back on the docs mix in technical complaints. What specific feedback did you get on the existing tutorial to prompt we need "better" tutorials?  What was your sample size and what were the comments about "better"

Looking at the stats on this page, visitors are not staying long enough to actually walk through the tutorial.  That doesn't necessarily mean the content fails there are a number of factors we should look at. I do need more data on the source for your comments on "better"

**Comment by shreyasthiagaraj** [comment]
Hey! Yea, I have to upload the new sample  code. I wanted to create a new
repo for that in the blockstack org but I don’t seem to have the
permissions for it. That will be up soon, but for now I’ve submitted the
app to the app store.

So the idea here was to create something like a quickstart for devs who are already familiar with iOS development. It’s not meant to be a tutorial or replace the existing one, but rather a complement. It also contains storage features that are not in the tutorial but will probably be in every app that is built. The final reason for it was to submit an app to the app store to see how the new “Sign In with Apple” would affect us.

The decision to create this was not a data driven one, but a hunch as to
how we can make it easier and faster to get started. If visitors are not
staying long enough to do the tutorial, perhaps downloading sample code
would be a better option. You’re right in that the solution does not make
for a tutorial or improve on the existing one, so perhaps the title here
can be changed to “iOS quickstart sample”.

**Comment by moxiegirl** [comment]
@shreyasthiagaraj  As I understand it:

* Something to submit to Apple ios App store for approval (with our auth)
* an app developers can run
* code experienced developers can review

Since a Quickstart is generally considered something with written docs and that isn't what we have here, I called it a demo app. Thanks for the suggestion to rename the ticket. Done.

**Comment by shreyasthiagaraj** [comment]
The app is on the App Store--it was approved without any hiccups. I've linked it on the blocksxack-ios GitHub page, and it will be mentioned at the top of the iOS SDK Tutorial as a way to get started with sample code.
